/******************************************************************************
 * @file a_temp.c
 * @author Seo Yujeong (yjseo@gst-in.com)
 * @brief 
 * @version 0.1
 * @date 2023-08-17
 * 
 * @copyright Copyright (c) 2023 Global Standard Technology Co., Ltd.
 * 
 * All rights reserved.
 * This file is part of closed source software.
 * Unauthorized reproduction and redistribution prohibited.
 *****************************************************************************/

#ifndef INC_A_CALIB_H_
#define INC_A_CALIB_H_

/*****************************************************************************/
/** INCLUDES *****************************************************************/
/*****************************************************************************/

/*****************************************************************************/
/** MACRO DEFINITIONS ********************************************************/
/*****************************************************************************/

#define CALIB_RTD_2X_SECTION					3
#define CALIB_RTD_SECTION						4
#define CALIB_TC_SECTION						2
#define CALIB_PGA_NUM							3	// 0 : RTD2X(PGA32), 1 : RTD(PGA16), 2 : TC(PGA64)

#define CALIB_SAVE_ERR_NONE						0
#define CALIB_SAVE_ERR_VALIDATION				12
#define CALIB_SAVE_ERR_EEPROM					20

typedef enum
{
	CALIB_SESSION_GROUP = 0,
	CALIB_SESSION_CHANNEL,
} calib_session_mode_et;

/* EEPR */
#define EEPR_CALIIB_START_ADDRESS				0x1000

#define EEPR_NUM_1SECTION						4
#define EEPR_ADC_1SECTION						3

#define	EEPR_SIZE_OFFSET						4
#define	EEPR_SIZE_GAIN							4
#define	EEPR_SIZE_BOUNDARY						4
#define	EEPR_SIZE_STATUS						4
#define	EEPR_SIZE_R								(EEPR_SIZE_OFFSET + EEPR_SIZE_GAIN + EEPR_SIZE_BOUNDARY + EEPR_SIZE_STATUS)

#define	EEPR_SIZE_ADC_OFFSET					4
#define	EEPR_SIZE_ADC_GAIN						4
#define EEPR_SIZE_ADC_STATUS					4
#define EEPR_SIZE_ADC							(EEPR_SIZE_ADC_OFFSET + EEPR_SIZE_ADC_GAIN + EEPR_SIZE_ADC_STATUS)

/*	CH1 offset, gain, boundary, status for 2XRTD, RTD, TC	*/
#define	EEPR_ADDR_CALIB_CHK						(EEPR_CALIIB_START_ADDRESS)
#define	EEPR_ADDR_2X_CH1_R1_OFFSET				(EEPR_ADDR_CALIB_CHK + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH1_R1_GAIN				(EEPR_ADDR_2X_CH1_R1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH1_R1_BD					(EEPR_ADDR_2X_CH1_R1_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH1_R1_STATUS				(EEPR_ADDR_2X_CH1_R1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_2X_CH1_R2_OFFSET				(EEPR_ADDR_2X_CH1_R1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_2X_CH1_R2_GAIN				(EEPR_ADDR_2X_CH1_R2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH1_R2_BD					(EEPR_ADDR_2X_CH1_R2_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH1_R2_STATUS				(EEPR_ADDR_2X_CH1_R2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_2X_CH1_R3_OFFSET				(EEPR_ADDR_2X_CH1_R2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_2X_CH1_R3_GAIN				(EEPR_ADDR_2X_CH1_R3_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH1_R3_BD					(EEPR_ADDR_2X_CH1_R3_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH1_R3_STATUS				(EEPR_ADDR_2X_CH1_R3_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH1_R1_OFFSET					(EEPR_ADDR_2X_CH1_R3_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH1_R1_GAIN					(EEPR_ADDR_CH1_R1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH1_R1_BD						(EEPR_ADDR_CH1_R1_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH1_R1_STATUS					(EEPR_ADDR_CH1_R1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH1_R2_OFFSET					(EEPR_ADDR_CH1_R1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH1_R2_GAIN					(EEPR_ADDR_CH1_R2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH1_R2_BD						(EEPR_ADDR_CH1_R2_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH1_R2_STATUS					(EEPR_ADDR_CH1_R2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH1_R3_OFFSET					(EEPR_ADDR_CH1_R2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH1_R3_GAIN					(EEPR_ADDR_CH1_R3_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH1_R3_BD						(EEPR_ADDR_CH1_R3_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH1_R3_STATUS					(EEPR_ADDR_CH1_R3_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH1_R4_OFFSET					(EEPR_ADDR_CH1_R3_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH1_R4_GAIN					(EEPR_ADDR_CH1_R4_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH1_R4_BD						(EEPR_ADDR_CH1_R4_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH1_R4_STATUS					(EEPR_ADDR_CH1_R4_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH1_TC1_OFFSET				(EEPR_ADDR_CH1_R4_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH1_TC1_GAIN					(EEPR_ADDR_CH1_TC1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH1_TC1_BD					(EEPR_ADDR_CH1_TC1_GAIN + EEPR_SIZE_GAIN)
#define	EEPR_ADDR_CH1_TC1_STATUS				(EEPR_ADDR_CH1_TC1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH1_TC2_OFFSET				(EEPR_ADDR_CH1_TC1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH1_TC2_GAIN					(EEPR_ADDR_CH1_TC2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH1_TC2_BD					(EEPR_ADDR_CH1_TC2_GAIN + EEPR_SIZE_GAIN)
#define	EEPR_ADDR_CH1_TC2_STATUS				(EEPR_ADDR_CH1_TC2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH1_ADC_RTD2X_OFFSET			(EEPR_ADDR_CH1_TC2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH1_ADC_RTD2X_GAIN			(EEPR_ADDR_CH1_ADC_RTD2X_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH1_ADC_RTD2X_STATUS			(EEPR_ADDR_CH1_ADC_RTD2X_GAIN + EEPR_SIZE_ADC_GAIN)

#define	EEPR_ADDR_CH1_ADC_RTD_OFFSET			(EEPR_ADDR_CH1_ADC_RTD2X_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_CH1_ADC_RTD_GAIN				(EEPR_ADDR_CH1_ADC_RTD_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH1_ADC_RTD_STATUS			(EEPR_ADDR_CH1_ADC_RTD_GAIN + EEPR_SIZE_ADC_GAIN)

#define	EEPR_ADDR_CH1_ADC_TC_OFFSET				(EEPR_ADDR_CH1_ADC_RTD_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_CH1_ADC_TC_GAIN				(EEPR_ADDR_CH1_ADC_TC_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH1_ADC_TC_STATUS				(EEPR_ADDR_CH1_ADC_TC_GAIN + EEPR_SIZE_ADC_GAIN)

/*	CH2 offset, gain, boundary, status for 2XRTD, RTD, TC	*/
#define	EEPR_ADDR_2X_CH2_R1_OFFSET				(EEPR_ADDR_CH1_ADC_TC_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_2X_CH2_R1_GAIN				(EEPR_ADDR_2X_CH2_R1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH2_R1_BD					(EEPR_ADDR_2X_CH2_R1_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH2_R1_STATUS				(EEPR_ADDR_2X_CH2_R1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_2X_CH2_R2_OFFSET				(EEPR_ADDR_2X_CH2_R1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_2X_CH2_R2_GAIN				(EEPR_ADDR_2X_CH2_R2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH2_R2_BD					(EEPR_ADDR_2X_CH2_R2_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH2_R2_STATUS				(EEPR_ADDR_2X_CH2_R2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_2X_CH2_R3_OFFSET				(EEPR_ADDR_2X_CH2_R2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_2X_CH2_R3_GAIN				(EEPR_ADDR_2X_CH2_R3_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH2_R3_BD					(EEPR_ADDR_2X_CH2_R3_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH2_R3_STATUS				(EEPR_ADDR_2X_CH2_R3_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH2_R1_OFFSET					(EEPR_ADDR_2X_CH2_R3_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH2_R1_GAIN					(EEPR_ADDR_CH2_R1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH2_R1_BD						(EEPR_ADDR_CH2_R1_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH2_R1_STATUS					(EEPR_ADDR_CH2_R1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH2_R2_OFFSET					(EEPR_ADDR_CH2_R1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH2_R2_GAIN					(EEPR_ADDR_CH2_R2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH2_R2_BD						(EEPR_ADDR_CH2_R2_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH2_R2_STATUS					(EEPR_ADDR_CH2_R2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH2_R3_OFFSET					(EEPR_ADDR_CH2_R2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH2_R3_GAIN					(EEPR_ADDR_CH2_R3_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH2_R3_BD						(EEPR_ADDR_CH2_R3_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH2_R3_STATUS					(EEPR_ADDR_CH2_R3_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH2_R4_OFFSET					(EEPR_ADDR_CH2_R3_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH2_R4_GAIN					(EEPR_ADDR_CH2_R4_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH2_R4_BD						(EEPR_ADDR_CH2_R4_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH2_R4_STATUS					(EEPR_ADDR_CH2_R4_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH2_TC1_OFFSET				(EEPR_ADDR_CH2_R4_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH2_TC1_GAIN					(EEPR_ADDR_CH2_TC1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH2_TC1_BD					(EEPR_ADDR_CH2_TC1_GAIN + EEPR_SIZE_GAIN)
#define	EEPR_ADDR_CH2_TC1_STATUS				(EEPR_ADDR_CH2_TC1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH2_TC2_OFFSET				(EEPR_ADDR_CH2_TC1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH2_TC2_GAIN					(EEPR_ADDR_CH2_TC2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH2_TC2_BD					(EEPR_ADDR_CH2_TC2_GAIN + EEPR_SIZE_GAIN)
#define	EEPR_ADDR_CH2_TC2_STATUS				(EEPR_ADDR_CH2_TC2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH2_ADC_RTD2X_OFFSET			(EEPR_ADDR_CH2_TC2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH2_ADC_RTD2X_GAIN			(EEPR_ADDR_CH2_ADC_RTD2X_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH2_ADC_RTD2X_STATUS			(EEPR_ADDR_CH2_ADC_RTD2X_GAIN + EEPR_SIZE_ADC_GAIN)

#define	EEPR_ADDR_CH2_ADC_RTD_OFFSET			(EEPR_ADDR_CH2_ADC_RTD2X_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_CH2_ADC_RTD_GAIN				(EEPR_ADDR_CH2_ADC_RTD_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH2_ADC_RTD_STATUS			(EEPR_ADDR_CH2_ADC_RTD_GAIN + EEPR_SIZE_ADC_GAIN)

#define	EEPR_ADDR_CH2_ADC_TC_OFFSET				(EEPR_ADDR_CH2_ADC_RTD_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_CH2_ADC_TC_GAIN				(EEPR_ADDR_CH2_ADC_TC_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH2_ADC_TC_STATUS				(EEPR_ADDR_CH2_ADC_TC_GAIN + EEPR_SIZE_ADC_GAIN)

/*	CH3 offset, gain, boundary, status for 2XRTD, RTD, TC	*/
#define	EEPR_ADDR_2X_CH3_R1_OFFSET				(EEPR_ADDR_CH2_ADC_TC_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_2X_CH3_R1_GAIN				(EEPR_ADDR_2X_CH3_R1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH3_R1_BD					(EEPR_ADDR_2X_CH3_R1_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH3_R1_STATUS				(EEPR_ADDR_2X_CH3_R1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_2X_CH3_R2_OFFSET				(EEPR_ADDR_2X_CH3_R1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_2X_CH3_R2_GAIN				(EEPR_ADDR_2X_CH3_R2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH3_R2_BD					(EEPR_ADDR_2X_CH3_R2_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH3_R2_STATUS				(EEPR_ADDR_2X_CH3_R2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_2X_CH3_R3_OFFSET				(EEPR_ADDR_2X_CH3_R2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_2X_CH3_R3_GAIN				(EEPR_ADDR_2X_CH3_R3_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH3_R3_BD					(EEPR_ADDR_2X_CH3_R3_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH3_R3_STATUS				(EEPR_ADDR_2X_CH3_R3_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH3_R1_OFFSET					(EEPR_ADDR_2X_CH3_R3_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH3_R1_GAIN					(EEPR_ADDR_CH3_R1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH3_R1_BD						(EEPR_ADDR_CH3_R1_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH3_R1_STATUS					(EEPR_ADDR_CH3_R1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH3_R2_OFFSET					(EEPR_ADDR_CH3_R1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH3_R2_GAIN					(EEPR_ADDR_CH3_R2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH3_R2_BD						(EEPR_ADDR_CH3_R2_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH3_R2_STATUS					(EEPR_ADDR_CH3_R2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH3_R3_OFFSET					(EEPR_ADDR_CH3_R2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH3_R3_GAIN					(EEPR_ADDR_CH3_R3_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH3_R3_BD						(EEPR_ADDR_CH3_R3_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH3_R3_STATUS					(EEPR_ADDR_CH3_R3_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH3_R4_OFFSET					(EEPR_ADDR_CH3_R3_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH3_R4_GAIN					(EEPR_ADDR_CH3_R4_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH3_R4_BD						(EEPR_ADDR_CH3_R4_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH3_R4_STATUS					(EEPR_ADDR_CH3_R4_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH3_TC1_OFFSET				(EEPR_ADDR_CH3_R4_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH3_TC1_GAIN					(EEPR_ADDR_CH3_TC1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH3_TC1_BD					(EEPR_ADDR_CH3_TC1_GAIN + EEPR_SIZE_GAIN)
#define	EEPR_ADDR_CH3_TC1_STATUS				(EEPR_ADDR_CH3_TC1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH3_TC2_OFFSET				(EEPR_ADDR_CH3_TC1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH3_TC2_GAIN					(EEPR_ADDR_CH3_TC2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH3_TC2_BD					(EEPR_ADDR_CH3_TC2_GAIN + EEPR_SIZE_GAIN)
#define	EEPR_ADDR_CH3_TC2_STATUS				(EEPR_ADDR_CH3_TC2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH3_ADC_RTD2X_OFFSET			(EEPR_ADDR_CH3_TC2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH3_ADC_RTD2X_GAIN			(EEPR_ADDR_CH3_ADC_RTD2X_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH3_ADC_RTD2X_STATUS			(EEPR_ADDR_CH3_ADC_RTD2X_GAIN + EEPR_SIZE_ADC_GAIN)

#define	EEPR_ADDR_CH3_ADC_RTD_OFFSET			(EEPR_ADDR_CH3_ADC_RTD2X_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_CH3_ADC_RTD_GAIN				(EEPR_ADDR_CH3_ADC_RTD_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH3_ADC_RTD_STATUS			(EEPR_ADDR_CH3_ADC_RTD_GAIN + EEPR_SIZE_ADC_GAIN)

#define	EEPR_ADDR_CH3_ADC_TC_OFFSET				(EEPR_ADDR_CH3_ADC_RTD_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_CH3_ADC_TC_GAIN				(EEPR_ADDR_CH3_ADC_TC_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH3_ADC_TC_STATUS				(EEPR_ADDR_CH3_ADC_TC_GAIN + EEPR_SIZE_ADC_GAIN)

/*	CH4 offset, gain, boundary, status for 2XRTD, RTD, TC	*/
#define	EEPR_ADDR_2X_CH4_R1_OFFSET				(EEPR_ADDR_CH3_ADC_TC_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_2X_CH4_R1_GAIN				(EEPR_ADDR_2X_CH4_R1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH4_R1_BD					(EEPR_ADDR_2X_CH4_R1_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH4_R1_STATUS				(EEPR_ADDR_2X_CH4_R1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_2X_CH4_R2_OFFSET				(EEPR_ADDR_2X_CH4_R1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_2X_CH4_R2_GAIN				(EEPR_ADDR_2X_CH4_R2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH4_R2_BD					(EEPR_ADDR_2X_CH4_R2_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH4_R2_STATUS				(EEPR_ADDR_2X_CH4_R2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_2X_CH4_R3_OFFSET				(EEPR_ADDR_2X_CH4_R2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_2X_CH4_R3_GAIN				(EEPR_ADDR_2X_CH4_R3_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_2X_CH4_R3_BD					(EEPR_ADDR_2X_CH4_R3_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_2X_CH4_R3_STATUS				(EEPR_ADDR_2X_CH4_R3_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH4_R1_OFFSET					(EEPR_ADDR_2X_CH4_R3_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH4_R1_GAIN					(EEPR_ADDR_CH4_R1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH4_R1_BD						(EEPR_ADDR_CH4_R1_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH4_R1_STATUS					(EEPR_ADDR_CH4_R1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH4_R2_OFFSET					(EEPR_ADDR_CH4_R1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH4_R2_GAIN					(EEPR_ADDR_CH4_R2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH4_R2_BD						(EEPR_ADDR_CH4_R2_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH4_R2_STATUS					(EEPR_ADDR_CH4_R2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH4_R3_OFFSET					(EEPR_ADDR_CH4_R2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH4_R3_GAIN					(EEPR_ADDR_CH4_R3_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH4_R3_BD						(EEPR_ADDR_CH4_R3_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH4_R3_STATUS					(EEPR_ADDR_CH4_R3_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH4_R4_OFFSET					(EEPR_ADDR_CH4_R3_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH4_R4_GAIN					(EEPR_ADDR_CH4_R4_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH4_R4_BD						(EEPR_ADDR_CH4_R4_GAIN + EEPR_SIZE_GAIN)	
#define	EEPR_ADDR_CH4_R4_STATUS					(EEPR_ADDR_CH4_R4_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH4_TC1_OFFSET				(EEPR_ADDR_CH4_R4_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH4_TC1_GAIN					(EEPR_ADDR_CH4_TC1_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH4_TC1_BD					(EEPR_ADDR_CH4_TC1_GAIN + EEPR_SIZE_GAIN)
#define	EEPR_ADDR_CH4_TC1_STATUS				(EEPR_ADDR_CH4_TC1_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH4_TC2_OFFSET				(EEPR_ADDR_CH4_TC1_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH4_TC2_GAIN					(EEPR_ADDR_CH4_TC2_OFFSET + EEPR_SIZE_OFFSET)
#define	EEPR_ADDR_CH4_TC2_BD					(EEPR_ADDR_CH4_TC2_GAIN + EEPR_SIZE_GAIN)
#define	EEPR_ADDR_CH4_TC2_STATUS				(EEPR_ADDR_CH4_TC2_BD + EEPR_SIZE_BOUNDARY)

#define	EEPR_ADDR_CH4_ADC_RTD2X_OFFSET			(EEPR_ADDR_CH4_TC2_OFFSET + EEPR_SIZE_R)
#define	EEPR_ADDR_CH4_ADC_RTD2X_GAIN			(EEPR_ADDR_CH4_ADC_RTD2X_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH4_ADC_RTD2X_STATUS			(EEPR_ADDR_CH4_ADC_RTD2X_GAIN + EEPR_SIZE_ADC_GAIN)

#define	EEPR_ADDR_CH4_ADC_RTD_OFFSET			(EEPR_ADDR_CH4_ADC_RTD2X_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_CH4_ADC_RTD_GAIN				(EEPR_ADDR_CH4_ADC_RTD_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH4_ADC_RTD_STATUS			(EEPR_ADDR_CH4_ADC_RTD_GAIN + EEPR_SIZE_ADC_GAIN)

#define	EEPR_ADDR_CH4_ADC_TC_OFFSET				(EEPR_ADDR_CH4_ADC_RTD_OFFSET + EEPR_SIZE_ADC)
#define	EEPR_ADDR_CH4_ADC_TC_GAIN				(EEPR_ADDR_CH4_ADC_TC_OFFSET + EEPR_SIZE_ADC_OFFSET)
#define	EEPR_ADDR_CH4_ADC_TC_STATUS				(EEPR_ADDR_CH4_ADC_TC_GAIN + EEPR_SIZE_ADC_GAIN)

#define EEPR_ADDR_CH1_CALIB_CHK					(EEPR_ADDR_CH4_ADC_TC_STATUS + EEPR_SIZE_ADC_STATUS)
#define EEPR_ADDR_CH2_CALIB_CHK					(EEPR_ADDR_CH1_CALIB_CHK + EEPR_SIZE_STATUS)
#define EEPR_ADDR_CH3_CALIB_CHK					(EEPR_ADDR_CH2_CALIB_CHK + EEPR_SIZE_STATUS)
#define EEPR_ADDR_CH4_CALIB_CHK					(EEPR_ADDR_CH3_CALIB_CHK + EEPR_SIZE_STATUS)
#define EEPR_CALIIB_END_ADDRESS					(EEPR_ADDR_CH4_CALIB_CHK + EEPR_SIZE_STATUS)

#if EEPR_CALIIB_END_ADDRESS > EEPR_MAX_SZ
#error not enough EEPROM spaces
#endif


/*****************************************************************************/
/** DATATYPES ****************************************************************/
/*****************************************************************************/
typedef struct Calib_Appl_struct
{
	float 					offset;
	float 					gain;
	int32_t 				boundary;
} Calib_Appl_st;

typedef struct Calib_AD7124_struct
{
	uint32_t				offset;
	uint32_t 				gain;
} Calib_AD7124_st;

typedef struct calib_struct
{
	struct
	{
		uint8_t On;
		uint8_t ch;
		uint8_t vaild_raw_value;
		uint8_t conv_ready;		// set when one calibration point measurement completes
		uint8_t conv_idx;		// which calibration point index just completed
		uint8_t save_error;		// CALIB_SAVE_ERR_* from the last ValidateAndSave call
		uint8_t save_diag_on;	// emit detailed EEPROM save diagnostics when non-zero
	} status;
	struct
	{
		Calib_Appl_st			RTD2X[ CALIB_RTD_2X_SECTION ];
		Calib_Appl_st			RTD[ CALIB_RTD_SECTION ];
		Calib_Appl_st			TC[ CALIB_TC_SECTION ];
		Calib_AD7124_st			AD7124[ CALIB_PGA_NUM ];
	} data[ MAX_TEMP_CHANNEL ];
	uint8_t (*Run)( sensor_et type, uint8_t ch, char cmd );
	uint8_t (*MeasurePoint)( sensor_et type, uint8_t ch, uint8_t idx, char cmd );
	float   (*GetConv)( sensor_et type, uint8_t ch, uint8_t idx );
	uint8_t (*ValidateAndSave)( sensor_et type, uint8_t ch );
	uint8_t (*ClearDoneFlag)( void );
	uint8_t (*StartSession)( calib_session_mode_et mode, uint8_t ch );
	uint8_t (*Complete)( uint8_t ch_mask );
	uint8_t (*IsDone)( void );
	uint8_t (*GetChannelDoneMask)( void );
} calib_st;

/*****************************************************************************/
/** GLOBAL VARIABLES *********************************************************/
/*****************************************************************************/
extern calib_st Calib;

/*****************************************************************************/
/** LOCAL VARIABLES **********************************************************/
/*****************************************************************************/
#if 0
typedef enum calib_type_enum
{
	CALIB_RESISTOR,
	CALIB_TC,
	CALIB_MAX_TYPE,
} calib_type_et;
#endif
/*****************************************************************************/
/** FUNCTION DEFINITIONS *****************************************************/
/*****************************************************************************/
void CalibrationInit( void );

#endif
